server.port=8280
spring.application.name=payment-app

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/shop-online
spring.r2dbc.username=postgres
spring.r2dbc.password=1234
spring.data.r2dbc.repositories.enabled=true

spring.datasource.hikari.initialization-fail-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=3

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/master