spring.application.name=shop-online

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/shop-online
spring.r2dbc.username=postgres
spring.r2dbc.password=1234
spring.data.r2dbc.repositories.enabled=true

spring.datasource.hikari.initialization-fail-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=3

spring.thymeleaf.enabled=true
spring.thymeleaf.suffix=.html
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.encoding=UTF-8

spring.webflux.charset=UTF-8

spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

payment-app.url=${PAYMENT_APP_URL:http://localhost:8280}

server.port=8180

spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://localhost:8080/realms/master/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.issuer-uri=${KEYCLOAK_ISSUE_URL:http://localhost:8080/realms/master}
spring.security.oauth2.client.registration.shoponline.provider=keycloak
spring.security.oauth2.client.registration.shoponline.authorizationGrantType=client_credentials
spring.security.oauth2.client.registration.shoponline.client-id=shop-online
spring.security.oauth2.client.registration.shoponline.client-secret=Y3A4O0mRyzMUCy79wvgbfbGDRvpzgYsd
spring.security.oauth2.client.registration.shoponline.scope=profile
spring.security.oauth2.client.registration.shoponline.clientAuthenticationMethod=client_secret_post