openapi: 3.0.3
info:
  title: PaymentApp API
  version: 1.0.0
paths:
  /getBalance:
    get:
      operationId: getBalance
      summary: Получить текущий баланс
      parameters:
        - name: userId
          in: query
          description: Идентификатор пользователя
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceInfo'
  /withdraw:
    put:
      operationId: withdraw
      summary: Списать со счета
      parameters:
        - name: userId
          in: query
          description: Идентификатор пользователя
          required: true
          schema:
            type: integer
            example: 1
        - name: amount
          in: query
          description: Сумма списания
          required: true
          schema:
            type: number
            example: 999.99
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceInfo'
components:
  schemas:
    BalanceInfo:
      type: object
      properties:
        userId:
          type: integer
          description: ИД пользователя
          example: 1
        currentValue:
          type: number
          description: Текущий баланс
          example: 9999.99